### ISSUE TITLE
Tutorial 05: trying my own .bmp files turns out black

### ISSUE THREAD

**Issue by leo-nerd** [opengl-tutorials/ogl#103]
Hello. I'm trying to replace the included .bmp textures with other images. I'm keeping them 512x512. The cube renders all black. What am I missing? Thanks.

**Comment by VBorisof** [comment]
Do you have anything reported to the console? Maybe file was not found.

**Comment by opengl-tutorial** [comment]
BMP has multiple format and we only support one in the loader.
as per:
http://www.opengl-tutorial.org/beginners-tutorials/tutorial-5-a-textured-cube/#loading-bmp-images-yourself

Our bmp loader is more for curious mind that want to see all the details.
Not really something that should be used anywhere.
Maybe you could instead use a proper image loading library like
https://github.com/nothings/stb for instance.

*Damien Mabin*
website: http://www.opengl-tutorial.org/  <http://www.opengl-tutorial.org/>
Game dev @ Supercell

**Comment by leo-nerd** [comment]
Right - that's what I suspected, thanks for the info!
