### ISSUE TITLE
Tutorial 4: Output looks nothing like what I have.

### ISSUE THREAD

**Issue by BlueStaggo** [opengl-tutorials/ogl#114]
Here is what the tutorial shows:
![A messy coloured cube with no z buffer.](https://www.opengl-tutorial.org/assets/images/tuto-4-colored-cube/missing_z_buffer.png)
And this is me at the same stage:
![A neat rainbow cube without a z buffer even though it looks like there is one there.](https://user-images.githubusercontent.com/71090710/127909150-f9bcda89-416b-4814-a57f-b84c6dfa63b5.png)
I'm using similar code, so they shouldn't be different. Are the screenshots for Tutorial 4 outdated or is there another problem?

**Comment by Garfield1002** [comment]
> Quick Note 1 : If you don’t see the problem, change your camera position to (4,3,-3)

Did you follow this step ?

**Comment by BlueStaggo** [comment]
No. The tutorial said nothing about that step.

**Comment by Garfield1002** [comment]
But did this step solve your issue?
