### ISSUE TITLE
glfw can't be created.

### ISSUE THREAD

**Issue by DeathPoem** [opengl-tutorials/ogl#14]
I was trying to make the tutorials work on my ubuntu 14.04 LTS which is installed in my vmWare ( a Nvida GPU of course ). But it seams that the glfw window can't be created correctly in the tutirial 1 : opening a window. I have google-ed for a while. Just need some help. 

window = glfwCreateWindow( 1024, 768, "Playground", NULL, NULL);

╭─frankwang@ubuntu ~/mycode/OpenGLTutorior/ogl-OpenGL-tutorial_0015_33/tutorial01_first_window/screenshots  
╰─➤  lspci |grep VGA
00:0f.0 VGA compatible controller: VMware SVGA II Adapter

would this be a problem to make it work?

**Comment by Calvin1602** [comment]
You need drivers for your GPU. Just a VGA controller won't do.
Generally speaking it's a pain on virtualized systems, but you can get it to work. I never used vmWare, but on VirtualBox you need to install OS Additions, and the proprietary drivers. 
If you can't get glxgears (or whatever) to run, the tutorials won't run either. Good luck !

**Comment by DeathPoem** [comment]
Thanks for your reply. As you say, to install a driver for my ubuntu is a little bit pain...I would try and thanks again for your feedback.

Send from nubia
