### ISSUE TITLE
CMP0026 is not known to this version of CMake.

### ISSUE THREAD

**Issue by mottosso** [opengl-tutorials/ogl#16]
On CMake 2.8.12.2 under Scientific Linux release 6.6 (Carbon), I got this error message during `cmake ..` followed by a halt.

```bash
CMake Error at CMakeLists.txt:24 (cmake_policy):
  Policy "CMP0026" is not known to this version of CMake.
```

Removing this line successfully got me past the error without any noticeable side-effects.

```bash
# On Visual 2005 and above, this module can set the debug working directory
# cmake_policy(SET CMP0026 OLD)
```

**Comment by opengl-tutorial** [comment]
This is CMake 3 specific. I hesitate between unsupporting CMake 2, and
checking the version...

**Comment by mottosso** [comment]
Do you mean you only support CMake 3, or that the problem only occurs with CMake 3?

**Comment by ph81323** [comment]
hi @mottosso , have you solved the problem yet? I have the same CMake version as you and got the same error as yours.

**Comment by mottosso** [comment]
Hey @ph81323, yes, as I said, I solved it by removing that line. I'd make a PR for it, but I'm not sure it affects other versions negatively.

**Comment by ph81323** [comment]
Thanks @mottosso , it solved!
