### ISSUE TITLE
Web Site Header Language Problem!

### ISSUE THREAD

**Issue by coderkan** [opengl-tutorials/ogl#69]
Hi ogl!

I think something is wrong. When I choice english language combobox, header language different from english it looks like Hungarian language.

Need to control and check Hungarian pull requests.  

![resim](https://user-images.githubusercontent.com/8382599/39627153-8619be24-4fad-11e8-949f-24a0195736da.png)

**Comment by Whiteseeker** [comment]
It's fixed here:
https://github.com/opengl-tutorials/ogl/commit/fc24bd43934602f4d3361ee3a58a2036072ea09d 

Thx for the report :)

**Comment by Whiteseeker** [comment]
PRobably in like 20 minute the website will be updated, clear you cache and you should be good :)

**Comment by coderkan** [comment]
Hi !
Everything is OK.
Successfully updated website.

Not at all :)
