### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by johannesugb** [opengl-tutorials/ogl#90]
May I ask what's the license of your OpenGL tutorials?
Btw: Thanks for them!

**Comment by pnbrown** [comment]
WTFPL

From http://www.opengl-tutorial.org/download/

> All the source code on this site (except third-party libraries) is released under the WTFPL Public Licence :
           DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
                   Version 2, December 2004
Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
Everyone is permitted to copy and distribute verbatim or modified
copies of this license document, and changing it is allowed as long
as the name is changed.
           DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
  TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
> 0. You just DO WHAT THE FUCK YOU WANT TO.

> All the tutorial material is available under Creative-Common license: CC-BY-NC-ND available here
