### ISSUE TITLE
Skybox please

### ISSUE THREAD

**Issue by FOLOME** [opengl-tutorials/ogl#96]
I have been looking for a good opengl tutorial and i find this cool one. I am using it in my project but a notice that it is not include skybox exemple.

So plz how to create a skybox ?

**Comment by VBorisof** [comment]
I think you can just create a huge cube, apply sky texture to it, and put yourself inside :)

**Comment by FOLOME** [comment]
Thank you for the replay, i have created a cube and i apply a cubemap texture to it, and before rendering it i used glDepthFunc(GL_LEQUAL) so everything else will be inside it.
Thank so much for those tutorials.
